### ISSUE TITLE
Falta preventDefault()

### ISSUE THREAD

**Issue by thehackermonkey** [klaushell/crapstablereloaded#1]
La app se recarga cada que das click a "roll dice" . Es posible que sea por que no tienes un e.preventDefault() en el click event.

https://github.com/klaushell/crapstablereloaded/blob/12c9027ad9f4903b87ba464e85e14506b7f97e1e/src/components/Player.jsx#L18

**Comment by klaushell** [comment]
Hola Hans,De hecho la estoy corriendo ahorita desde Heroku y está corriendo sin ningún problema.El código de Heroku se manda automáticamente con cada push de Github, debería tener la misma versión.Necesitamos indagar un poco más, te mando un mensaje por Telegram. Gracias.  Sent from Mail for Windows 10 From: HansSent: 10 May 2021 08:46To: klaushell/crapstablereloadedCc: SubscribedSubject: [klaushell/crapstablereloaded] Falta preventDefault() (#1) La app se recarga cada que das click a "roll dice" . Es posible que sea por que no tienes un e.preventDefault() en el click event.https://github.com/klaushell/crapstablereloaded/blob/12c9027ad9f4903b87ba464e85e14506b7f97e1e/src/components/Player.jsx#L18—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by klaushell** [comment]
> La app se recarga cada que das click a "roll dice" . Es posible que sea por que no tienes un e.preventDefault() en el click event.
> 
> https://github.com/klaushell/crapstablereloaded/blob/12c9027ad9f4903b87ba464e85e14506b7f97e1e/src/components/Player.jsx#L18

Extraña situación, esta aplicación fue probada en diferentes navegadores y estaba funcional. De todas formas se agregó la linea al código! Muchas gracias!
